clc; clear;
f = @(x) x.*sin(3*x);
a = 0;
b = 1;
N = 100;
disp('Метод правых прямоугольников: ');
disp(right_rect(f, a, b, N));
disp('Метод левых прямоугольников: ');
disp(left_rect(f, a, b, N));
disp('Метод средних прямоугольников: ');
disp(middle_rect(f, a, b, N));
disp('Метод трапеций: ');
disp(trapezoidal(f, a, b, N));
disp('Метод Симпсона: ');
disp(simpson(f, a, b, N));
disp('Символьное интегрирование: ');
syms x;
I = int(f, x, a, b);
disp(double(I));